#!/bin/sh
echo f > /sys/class/net/br-lan/queues/rx-0/rps_cpus
echo f > /sys/class/net/wwan0/queues/rx-0/rps_cpus
echo f > /sys/class/net/wwan0_1/queues/rx-0/rps_cpus
echo f > /sys/class/net/wifi0/queues/rx-0/rps_cpus
echo f > /sys/class/net/wifi1/queues/rx-0/rps_cpus
echo f > /sys/class/net/eth0/queues/rx-0/rps_cpus
echo f > /sys/class/net/eth0/queues/rx-0/rps_cpus
echo f > /sys/class/net/eth1/queues/rx-0/rps_cpus
echo f > /sys/class/net/eth2/queues/rx-0/rps_cpus
echo f > /sys/class/net/eth3/queues/rx-0/rps_cpus
echo f > /sys/class/net/eth4/queues/rx-0/rps_cpus
EOF
