#!/bin/sh
clear
echo -e "\e[1;36m======================================\e[0m"
echo -e "\e[1;37m Autoscript Package QWRT By \e[1;32m@XoolVPN\e[0m"
echo -e "\e[1;36m======================================\e[0m"
echo
sleep 2

sed -i '/done/iiptables -t mangle -I POSTROUTING -o wwan0 -j TTL --ttl-set 64\niptables -t mangle -I POSTROUTING -o br-lan -j TTL --ttl-set 64\niptables -t mangle -I PREROUTING -i wwan0 -j TTL --ttl-set 64\niptables -t mangle -I PREROUTING -i br-lan -j TTL --ttl-set 64\niptables -t mangle -A POSTROUTING -j TTL --ttl-set 64\niptables -t mangle -A PREROUTING -j TTL --ttl-set 64' /etc/hotplug.d/iface/19-rooter
sed -i '/done/iiptables -t mangle -I POSTROUTING -o wwan0_1 -j TTL --ttl-set 64\niptables -t mangle -I POSTROUTING -o br-lan -j TTL --ttl-set 64\niptables -t mangle -I PREROUTING -i wwan0_1 -j TTL --ttl-set 64\niptables -t mangle -I PREROUTING -i br-lan -j TTL --ttl-set 64' /etc/hotplug.d/iface/19-rooter

execute_install() {
    local cmd="$1"
    local message="$2"
    echo -n -e "\e[0;37m$message...\e[0m"
    eval "$cmd" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo -e "\r\e[0;37m$message...\e[0m\e[1;32mDone!\e[0m"
    else
        echo -e "\r\e[1;31m$message...Failed!\e[0m"
    fi
}

execute_install "opkg update; opkg install htop; opkg install vsftpd" "Update all packages. Please wait"
opkg --force-removal-of-dependent-packages remove luci-app-openclash luci-app-ipsec-server luci-app-openvpn-server openvpn-openssl openvpn-easy-rsa iperf ppp-mod-pppoe ppp
wget -q -O /usr/lib/lua/luci/model/cbi/rooter/customize.lua "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/customize.lua
wget -q -O /usr/lib/lua/luci/model/cbi/rooter/profiles.lua "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/profiles.lua
wget -q -O /usr/lib/lua/luci/controller/admin/modem.lua "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/modem.lua
wget -q -O /usr/lib/lua/luci/controller/modlog.lua "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/modlog.lua
wget -q -O /usr/lib/lua/luci/controller/sms.lua "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/sms.lua
wget -q -O /usr/lib/lua/luci/view/rooter/debug.htm "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/debug.htm
wget -q -O /usr/lib/lua/luci/view/rooter/misc.htm "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/misc.htm
wget -q -O /usr/lib/lua/luci/view/rooter/custom.htm "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/custom.htm
wget -q -O /usr/lib/lua/luci/view/rooter/net_status.htm "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/net_status.htm
wget -q -O /usr/lib/lua/luci/view/rooter/sms.htm "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/sms.htm
wget -q -O /usr/lib/lua/luci/view/modlog/modlog.htm "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/modlog.htm
wget -q -O /usr/bin/speedtest "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/speedtest"; chmod +x /usr/bin/speedtest
uci set turboacc.config.bbr_cca='1'; uci commit turboacc.config
uci set cpufreq.cpufreq.governor='performance'; uci commit cpufreq.cpufreq
uci set cpufreq.cpufreq.minifreq='2208000'; uci commit cpufreq.cpufreq
uci set dhcp.lan.dhcp_option='6,1.1.1.1,1.0.0.1'; uci commit dhcp.lan
execute_install "uci set luci.main.lang='en'; uci commit" "Set language to English"
execute_install "uci set system.@system[0].zonename='Asia/Kuala Lumpur'; uci commit system" "Set timezone to Asia/Kuala Lumpur"
execute_install "uci -q delete system.ntp.server; uci add_list system.ntp.server='time.cloudflare.com'; uci commit system.ntp; /etc/init.d/sysntpd restart" "Configuring and restart NTP service"
execute_install "uci set network.wan.ifname='wwan0_1'; uci commit network.wan" "Setting WAN interface network"
execute_install "uci set network.wan6.ifname='wwan0_1'; uci commit network.wan6" "Setting WAN6 interface network"
execute_install "wget -q -O /root/luci-app-passwall.ipk "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/luci-app-passwall.ipk"; chmod +x /root/luci-app-passwall.ipk; opkg install *.ipk --force-depends; cd /tmp;curl -L https://github.com/mssvpn/Xray-core/releases/download/v1.7.2.1/Xray-linux-arm64-v8a.zip > Xray-linux-arm64-v8a.zip && unzip *.zip && mv xray /usr/bin && chmod +x /usr/bin/xray" "Installing Passwall. Please wait"

cat << 'EOF' > /etc/hotplug.d/iface/99-passwall
#!/bin/sh

log () {
 modlog "$@"
}

if [ "$ACTION" = "ifup" -a $INTERFACE = wan  -a $(uci -q get passwall.@global[0].enabled) -eq 1 ]; then
 sleep 10
 /etc/init.d/passwall restart
 if [ $? -eq 0 ]; then
  log "Restart Passwall"
 else
  log "failed to restart Passwall"
 fi
fi
done
EOF

rm -f /root/luci-app-passwall.ipk

cat << 'EOF' > /root/setcpu.sh
#!/bin/sh

INTERRUPT=$(ls /proc/irq/ | sed '/default/d')
USB3_NUMBER=$(grep usb3 /proc/interrupts | awk -F: '{print $1}' | sed 's/^ //')

for I in ${INTERRUPT}; do
 if [[ ${I} = ${USB3_NUMBER} ]]; then
         echo f > /proc/irq/${I}/smp_affinity 2>/dev/null
        else
         echo e > /proc/irq/${I}/smp_affinity 2>/dev/null
        fi
        printf "%-10s" ${I}:
        cat /proc/irq/${I}/smp_affinity
done
EOF

if [[ -z /etc/hotplug.d/net/20-smp-tune.bak ]]; then
    cp /etc/hotplug.d/net/20-smp-tune /etc/hotplug.d/net/20-smp-tune.bak
fi

cat << 'EOF' > /etc/hotplug.d/net/20-smp-tune
#!/bin/sh
echo f > /sys/class/net/br-lan/queues/rx-0/rps_cpus
echo f > /sys/class/net/wwan0_1/queues/rx-0/rps_cpus
echo f > /sys/class/net/wifi0/queues/rx-0/rps_cpus
echo f > /sys/class/net/wifi1/queues/rx-0/rps_cpus
EOF

rm -rf /root/setcpu.sh
echo
echo -ne "\e[1;32mSuccessful!\e[0m \e[0;37mReboot Now? (y/n)? : \e[0m"
read answer
if [ "$answer" == "${answer#[Yy]}" ] ;then
    echo -e "\e[1;31mReboot skipped. Please reboot manually for changes to take effect.\e[0m"
    exit 0
else
    echo -e "\e[1;32mRebooting...\e[0m"
    reboot
fi
