#!/bin/sh
clear
echo -e "\e[1;36m=============================================\e[0m"
echo -e "\e[1;37m     Autoscript TuneCPU QWRT By\e[0m \e[1;32m@XoolVPN\e[0m"
echo -e "\e[1;36m=============================================\e[0m"
echo
sleep 2

execute_and_check() {
    local cmd="$1"
    local message="$2"
    echo -n -e "\e[1;37m$message...\e[0m"
    eval "$cmd" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo -e "\r\e[1;37m$message...\e[0m\e[1;32mDone!\e[0m"
    else
        echo -e "\r\e[1;31m$message...Failed!\e[0m"
    fi
}

wget -q -O /etc/config/rirq "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/rirq";
wget -q -O /etc/hotplug.d/iface/82-irqbalance "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/82-irqbalance";
wget -q -O /etc/hotplug.d/net/97-smp-tune "https://raw.githubusercontent.com/tryoo127/Aw-Packages/main/system/97-smp-tune";
execute_and_check "uci set turboacc.config.bbr_cca='1'; uci commit turboacc.config" "Tuning CPU Modem performance"
execute_and_check "uci set cpufreq.cpufreq.governor='performance'; uci commit cpufreq.cpufreq" "Set CPU to maximum frequency"
uci set cpufreq.cpufreq.minifreq='2208000'; uci commit cpufreq.cpufreq
uci set dhcp.lan.dhcp_option='6,1.1.1.1,1.0.0.1'; uci commit dhcp.lan
sleep 3

rm -f /root/tunecpu
echo
echo -ne "\e[1;32mSuccessful!\e[0m \e[0;37mReboot Now? (y/n)? : \e[0m"
read answer
if [ "$answer" == "${answer#[Yy]}" ] ;then
    echo -e "\e[1;31mReboot skipped. Please reboot manually for changes to take effect.\e[0m"
    exit 0
else
    echo -e "\e[1;32mRebooting...\e[0m"
    reboot
fi
